// io-playground-angular/src/app/pages/form/form.component.ts
import { Component, signal, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { JsonPipe } from '@angular/common';

@Component({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [JsonPipe],
  template: `
    <main>
      <h1>Forms — FACE Participation Test</h1>
      <form (submit)="handleSubmit($event)" style="display: flex; flex-direction: column; gap: 1rem; max-width: 400px;">
        <io-input label="Full name" name="name" required></io-input>
        <io-input label="Email" name="email" type="email" required></io-input>
        <io-select label="Role" name="role">
          <option value="">Select role</option>
          <option value="dev">Developer</option>
          <option value="design">Designer</option>
        </io-select>
        <io-checkbox label="I agree to terms" name="terms" required></io-checkbox>
        <io-button type="submit">Submit</io-button>
      </form>
      @if (submitted()) {
        <div class="result" data-testid="result">
          <pre>{{ submitted() | json }}</pre>
        </div>
      }
    </main>
  `,
})
export class FormComponent {
  submitted = signal<Record<string, FormDataEntryValue> | null>(null);

  handleSubmit(e: Event) {
    e.preventDefault();
    const data = new FormData(e.target as HTMLFormElement);
    this.submitted.set(Object.fromEntries(data.entries()));
  }
}

// io-playground-react/app/form/page.tsx
'use client';

import { useState } from 'react';
import { IoInput, IoSelect, IoCheckbox, IoRadio, IoButton } from '@iodigital-com/components-react';

export default function FormPage() {
  const [submitted, setSubmitted] = useState<Record<string, string> | null>(null);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    setSubmitted(Object.fromEntries(data.entries()) as Record<string, string>);
  };

  return (
    <main>
      <h1>Forms — FACE Participation Test</h1>
      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxWidth: '400px' }}>
        <IoInput label="Full name" name="name" required />
        <IoInput label="Email" name="email" type="email" required />
        <IoSelect label="Role" name="role">
          <option value="">Select role</option>
          <option value="dev">Developer</option>
          <option value="design">Designer</option>
          <option value="pm">Product Manager</option>
        </IoSelect>
        <IoCheckbox label="I agree to terms" name="terms" required />
        <div style={{ display: 'flex', gap: '1rem' }}>
          <IoRadio label="Option A" name="choice" value="a" />
          <IoRadio label="Option B" name="choice" value="b" />
        </div>
        <IoButton type="submit">Submit</IoButton>
      </form>
      {submitted && (
        <div className="result" data-testid="result">
          <pre>{JSON.stringify(submitted, null, 2)}</pre>
        </div>
      )}
    </main>
  );
}
