// io-playground-react/app/button/page.tsx
'use client';

import { useState } from 'react';
import { IoButton } from '@iodigital-com/components-react';

export default function ButtonPage() {
  const [count, setCount] = useState(0);

  return (
    <main>
      <h1>io-button — Click Event Test</h1>
      <IoButton onClick={() => setCount(c => c + 1)}>Click me</IoButton>
      <IoButton variant="ghost" onClick={() => setCount(0)} style={{ marginLeft: '0.5rem' }}>Reset</IoButton>
      <div className="result" data-testid="result">Click count: {count}</div>
    </main>
  );
}

// io-playground-angular/src/app/pages/button/button.component.ts
import { Component, signal, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <main>
      <h1>io-button — Click Event Test</h1>
      <io-button (click)="count.update(c => c + 1)">Click me</io-button>
      <io-button variant="ghost" (click)="count.set(0)" style="margin-left: 0.5rem">Reset</io-button>
      <div class="result" data-testid="result">Click count: {{ count() }}</div>
    </main>
  `,
})
export class ButtonComponent {
  count = signal(0);
}
