// io-playground-react/app/modal/page.tsx
'use client';

import { useState } from 'react';
import { IoButton, IoModal, IoInput } from '@iodigital-com/components-react';

export default function ModalPage() {
  const [open, setOpen] = useState(false);
  const [result, setResult] = useState('');
  const [name, setName] = useState('');

  const handleCancel = () => {
    setOpen(false);
    setResult('cancel-clicked');
  };

  const handleSave = () => {
    if (!name.trim()) {
      setResult('validation-error: name is required');
      return;
    }
    setOpen(false);
    setResult(`saved: ${name}`);
  };

  return (
    <main>
      <h1>io-modal — Footer Button Click Test</h1>

      <IoButton onClick={() => { setOpen(true); setResult(''); }}>
        Open modal
      </IoButton>

      <div className="result" data-testid="result">{result || 'No action yet'}</div>

      <IoModal
        open={open}
        heading="Create item"
        onDismiss={handleCancel}
      >
        <IoInput
          label="Name"
          name="name"
          value={name}
          onInput={(e: CustomEvent) =>
            setName((e.target as HTMLInputElement).value)
          }
        />

        <IoButton
          slot="footer"
          variant="ghost"
          onClick={handleCancel}
        >
          Cancel
        </IoButton>
        <IoButton
          slot="footer"
          onClick={handleSave}
        >
          Save
        </IoButton>
      </IoModal>
    </main>
  );
}

// io-playground-angular/src/app/pages/modal/modal.component.ts
import { Component, signal, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <main>
      <h1>io-modal — Footer Button Click Test</h1>

      <io-button (click)="openModal()">Open modal</io-button>

      <div class="result" data-testid="result">{{ result() || 'No action yet' }}</div>

      <io-modal
        [attr.open]="modalOpen() ? '' : null"
        heading="Create item"
        (dismiss)="handleCancel()"
      >
        <io-input
          label="Name"
          name="name"
          [attr.value]="name()"
          (input)="name.set($any($event.target).value)"
        ></io-input>

        <io-button
          slot="footer"
          variant="ghost"
          (click)="handleCancel()"
        >Cancel</io-button>
        <io-button
          slot="footer"
          (click)="handleSave()"
        >Save</io-button>
      </io-modal>
    </main>
  `,
})
export class ModalComponent {
  modalOpen = signal(false);
  result = signal('');
  name = signal('');

  openModal() {
    this.modalOpen.set(true);
    this.result.set('');
  }

  handleCancel() {
    this.modalOpen.set(false);
    this.result.set('cancel-clicked');
  }

  handleSave() {
    if (!this.name().trim()) {
      this.result.set('validation-error: name is required');
      return;
    }
    this.modalOpen.set(false);
    this.result.set('saved: ' + this.name());
  }
}
